### ISSUE TITLE
Device tree for Lineage 16

### ISSUE THREAD

**Issue by Jackychans** [synt4x93/android_kernel_samsung_exynos990#1]
Could you guide me through where to get all device tree of S9 of lineageos 16 ? I really need to **build ROM for S9 from source**

The reason is that I got some project required S9 lineageos for testing. However, official lineage 17.1 does not pass safetynet while 18.1 is way too new.

I'm willing to donate paypal as much as I could to get your help, please ...I've ping you through forum but not sure if you're online

**Comment by synt4x93** [comment]
Sorry did not see the forum, hmm that's strange I can pass safetynet fine on 17.1/18.1 if I use the usual hacks (force basic key attestation + set fingerprint + enable magisk hide)

If you really need my old los16 trees I can find them and give to you... but it's half broken I wouldn't suggest running it at all if you can help it  (SELinux Permissive and some big hacks for mobile network signal indicator on statusbar) that's why I removed from my git when we moved to 17.1
